# Site configuration

title: Sud Web
tagline: les 27 et 28 mai 2016 à Bordeaux
description: Deux journées pour faire le plein d'inspiration entre super-héros du web.
logo: images/logo-sud-web.png
locale: fr
url: http://sudweb.fr
repository: sudweb/2016
baseurl: /2016
twitter:
  username: SudWeb

social:
  type: organization
  links:
    - https://twitter.com/SudWeb
    - https://www.facebook.com/SudWeb
    - http://lanyrd.com/series/sudweb/

# Services configuration

analytics:
  google :
    tracking_id : "UA-22076213-1"

weezevent:
    mini-site-url: https://www.weezevent.com/sudweb-2016

newsletter:
  url: http://sudweb.us2.list-manage.com/subscribe?u=af19b58cf514c01eca3f7652e&id=b579f5b507

# Jekyll configuration

permalink: /:title/
paginate: 5
timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

collections:
  talks:
    output: false
    order: date asc
    permalink: /talks/:path/
    sitemap: false
  components:
    output: false
  colors:
    output: false

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script

gems:
- jekyll-github-metadata
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- octopress-autoprefixer
